### Question 1
Given the following confusion matrix from a spam filter (Actual: Spam=70, Not Spam=130; Predicted: Spam=60, Not Spam=140; TP=50, TN=120, FP=10, FN=20), manually calculate the values of accuracy, precision, recall, and F1 score on paper or in a Jupyter notebook.

The evaluation metrics are calculated as follows:

- **Accuracy** $= \frac{TP + TN}{TP + TN + FP + FN} = \frac{50 + 120}{50 + 120 + 10 + 20} = \frac{170}{200} = 0.8500$ (85.00%)
- **Precision** $= \frac{TP}{TP + FP} = \frac{50}{50 + 10} = \frac{50}{60} \approx 0.8333$ (83.33%)
- **Recall** $= \frac{TP}{TP + FN} = \frac{50}{50 + 20} = \frac{50}{70} \approx 0.7143$ (71.43%)
- **F1 Score** $= 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}} = 2 \times \frac{0.8333 \times 0.7143}{0.8333 + 0.7143} \approx 0.7692$ (76.92%)

In [3]:
# Given confusion matrix parameters for spam filter
tp = 50
tn = 120
fp = 10
fn = 20

# Calculations
total = tp + tn + fp + fn
accuracy = (tp + tn) / total
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print(f"Total Samples:       {total}")
print(f"Accuracy:            {accuracy:.4f} ({accuracy * 100:.2f}%)")
print(f"Precision:           {precision:.4f} ({precision * 100:.2f}%)")
print(f"Recall:              {recall:.4f} ({recall * 100:.2f}%)")
print(f"F1 Score:            {f1:.4f} ({f1 * 100:.2f}%)")

Total Samples:       200
Accuracy:            0.8500 (85.00%)
Precision:           0.8333 (83.33%)
Recall:              0.7143 (71.43%)
F1 Score:            0.7692 (76.92%)


### Question 2
Write a Python function called print_confusion_matrix(tp, tn, fp, fn) that prints the confusion matrix in a readable table format for any given values of true positives, true negatives, false positives, and false negatives.

A structured $2 \times 2$ grid organizes predictions against ground truth outcomes, positioning True Positives and True Negatives on the main diagonal to highlight accurate classifications versus misclassification trade-offs (False Positives and False Negatives).

In [4]:
import pandas as pd

def print_confusion_matrix(tp, tn, fp, fn):
    cm_df = pd.DataFrame(
        data=[[tp, fn], [fp, tn]],
        index=['Actual Positive (1)', 'Actual Negative (0)'],
        columns=['Pred Positive (1)', 'Pred Negative (0)']
    )
    print("=" * 48)
    print("               CONFUSION MATRIX")
    print("=" * 48)
    display(cm_df)
    print(f"\nSummary: TP={tp}, FN={fn} | FP={fp}, TN={tn}")
    return cm_df

# Test function with Question 1 values
_ = print_confusion_matrix(tp=50, tn=120, fp=10, fn=20)

               CONFUSION MATRIX


,Pred Positive (1),Pred Negative (0)
Actual Positive (1),50,20
Actual Negative (0),10,120



Summary: TP=50, FN=20 | FP=10, TN=120


### Question 3
Imagine you are evaluating a fake news detection model for a social media app. The model flagged 80 posts as fake, of which 60 were actually fake (TP), and missed 30 fake posts (FN). There were 120 posts correctly identified as not fake (TN), and 10 real posts wrongly flagged as fake (FP). Calculate and print the precision and recall for this model.

*(Hint: Precision = TP / (TP + FP), Recall = TP / (TP + FN))*

For the fake news detection model with $\text{TP}=60$, $\text{FP}=10$, and $\text{FN}=30$:

- **Precision** $= \frac{TP}{TP + FP} = \frac{60}{60 + 10} = \frac{60}{70} \approx 0.8571$ (85.71% of posts flagged as fake were genuinely fake)
- **Recall** $= \frac{TP}{TP + FN} = \frac{60}{60 + 30} = \frac{60}{90} \approx 0.6667$ (66.67% of all actual fake posts were successfully detected)

In [5]:
# Fake news detection model values
tp_fake = 60
fp_fake = 10
fn_fake = 30
tn_fake = 120

# Calculate precision and recall
precision_fake = tp_fake / (tp_fake + fp_fake)
recall_fake = tp_fake / (tp_fake + fn_fake)

print(f"Fake News Model Precision: {precision_fake:.4f} ({precision_fake * 100:.2f}%)")
print(f"Fake News Model Recall:    {recall_fake:.4f} ({recall_fake * 100:.2f}%)")

Fake News Model Precision: 0.8571 (85.71%)
Fake News Model Recall:    0.6667 (66.67%)


### Question 4
Given a confusion matrix for a food delivery fraud detection system (TP=40, TN=150, FP=20, FN=10), write Python code to compute the F1 score and explain in one line what the F1 score tells you about the model's performance.

*(Hint: F1 = 2 * (precision * recall) / (precision + recall))*

Using $\text{Precision} = \frac{40}{40 + 20} = 0.6667$ and $\text{Recall} = \frac{40}{40 + 10} = 0.8000$, the model achieves an **F1 score of 0.7273 (72.73%)**.
The F1 score measures the harmonic mean of precision and recall, indicating how effectively the model balances catching actual fraudulent orders without overburdening operations with false fraud accusations on legitimate customers.

In [6]:
# Food delivery fraud detection values
tp_fraud = 40
tn_fraud = 150
fp_fraud = 20
fn_fraud = 10

# Compute Precision, Recall, and F1 score
prec_fraud = tp_fraud / (tp_fraud + fp_fraud)
rec_fraud = tp_fraud / (tp_fraud + fn_fraud)
f1_fraud = 2 * (prec_fraud * rec_fraud) / (prec_fraud + rec_fraud)

print(f"Precision: {prec_fraud:.4f} ({prec_fraud * 100:.2f}%)")
print(f"Recall:    {rec_fraud:.4f} ({rec_fraud * 100:.2f}%)")
print(f"F1 Score:  {f1_fraud:.4f} ({f1_fraud * 100:.2f}%)")
print("\nInterpretation: The F1 score indicates a strong balance between detecting fraud (80.0% recall) while maintaining acceptable precision (66.7%) under class imbalance.")

Precision: 0.6667 (66.67%)
Recall:    0.8000 (80.00%)
F1 Score:  0.7273 (72.73%)

Interpretation: The F1 score indicates a strong balance between detecting fraud (80.0% recall) while maintaining acceptable precision (66.7%) under class imbalance.
